# Generated by Django 5.1.6 on 2025-02-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('release_year', models.IntegerField()),
                ('is_rented', models.BooleanField()),
                ('car_photo', models.ImageField(default='car_photos/car_default.jpg', upload_to='car_photos')),
            ],
        ),
    ]
