# Generated by Django 5.1.6 on 2025-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(default='car_photos/car_default.jpg', upload_to='car_photos/'),
        ),
    ]
