# Generated by Django 5.1.6 on 2025-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_car_photo_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
