# Generated by Django 5.1.6 on 2025-02-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_customuser_profile_photo_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default_profile_photo.png', null=True, upload_to='profile_photos/'),
        ),
    ]
