# Generated by Django 5.1.6 on 2025-03-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_messages_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_messages_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
